---
- name: Check VM Power State
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Gather vmware host facts
      community.vmware.vmware_host_facts:
        hostname: "172.21.131.220"
        username: "root"
        password: "my_passwd"
        validate_certs: no
      register: host_facts

    - name: Get VM power state
      community.vmware.vmware_vm_info:
        hostname: "172.21.131.220"
        username: "root"
        password: "my_passwd"
        validate_certs: no
      register: vm_info

    - name: Display VM power state
      debug:
        var: vm_info


